--非分区表insert into
drop table if exists vipdmt.query105_test;
create table if not exists vipdmt.query105_test like vipce.vchat_chatinfo_detail ;
insert overwrite table vipdmt.query105_test
select
    cih_id
     ,cih_queue_endtime
     ,cih_finishtime
     ,time_length
     ,cih_client_loginname
     ,cu_username
     ,cih_service_senderid
     ,kfxxs
     ,fkxxs
     ,cih_avg_time
     ,msg
     ,cih_client_address
     ,cih_client_ip
     ,cih_client_b2cuserid
     ,queue_code
     ,source
     ,vmark_name
     ,cih_grade
     ,close_reason
     ,gongdan_no
     ,wtnm1
     ,wtnm2
     ,wtnm3
     ,order_sn
     ,cih_last_chatid
     ,is_new_man
     ,cih_client_tags
     ,star
     ,content
     ,suggestion
     ,cih_transfer_flag
     ,cd_deptname
     ,cih_source_url
     ,cih_product
     ,cih_q_product_id
     ,cih_q_order_sn
     ,cih_brand_store_sn
     ,cih_schedule_name
     ,cih_robotid
     ,cih_vendor_skip_type
     ,cih_vendornum
     ,cat1_name_new
     ,cat2_name_new
     ,cat3_name_new
     ,msg_01
from vipce.vchat_chatinfo_detail;
insert into table vipdmt.query104_test
select
    cih_id
     ,cih_queue_endtime
     ,cih_finishtime
     ,time_length
     ,cih_client_loginname
     ,cu_username
     ,cih_service_senderid
     ,kfxxs
     ,fkxxs
     ,cih_avg_time
     ,msg
     ,cih_client_address
     ,cih_client_ip
     ,cih_client_b2cuserid
     ,queue_code
     ,source
     ,vmark_name
     ,cih_grade
     ,close_reason
     ,gongdan_no
     ,wtnm1
     ,wtnm2
     ,wtnm3
     ,order_sn
     ,cih_last_chatid
     ,is_new_man
     ,cih_client_tags
     ,star
     ,content
     ,suggestion
     ,cih_transfer_flag
     ,cd_deptname
     ,cih_source_url
     ,cih_product
     ,cih_q_product_id
     ,cih_q_order_sn
     ,cih_brand_store_sn
     ,cih_schedule_name
     ,cih_robotid
     ,cih_vendor_skip_type
     ,cih_vendornum
     ,cat1_name_new
     ,cat2_name_new
     ,cat3_name_new
     ,msg_01
from vipce.vchat_chatinfo_detail ;